export const fontSizes = {
  categoryButton: 16,
  homeLogin: 16,
  homeStoryHeadings: 22,
  headerHeading: 24,
  authHeading: 30,
  authDescription: 16,
  inputText: 18,
  inputLable: 15,
  authButton: 20,
  authBackLink: 16,
  remeberNTerms: 15,
  authBottom: 16,
  profileList: 16,
  profileName: 22,
  profileUsername: 16,
  deleteButon: 18,
  memberSince: 14,
  contentHeading: 24,
  pagesHeading: 20,
  contentText: 15,
  counterText: 15,
  share: 15,
  contentCardText: 15,
  contentCardBottom: 13,
  splashSlogan: 24,
};
